# Generated by Django 6.0.3 on 2026-03-06 07:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], db_index=True, default='active', max_length=20)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.school')),
            ],
            options={
                'db_table': 'accounts_teacher',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['school', 'last_name', 'first_name'], name='idx_teacher_school_name'), models.Index(fields=['school', 'status'], name='idx_teacher_school_status')],
                'constraints': [models.UniqueConstraint(fields=('school', 'email'), name='uniq_teacher_email_per_school')],
            },
        ),
    ]
