# Generated by Django 6.0.3 on 2026-03-07 15:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_school_branding_and_next_term_begins'),
        ('enrollment', '0004_parent_and_studentparent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('result', 'Result'), ('attendance', 'Attendance'), ('finance', 'Finance'), ('general', 'General'), ('announcement', 'Announcement')], db_index=True, default='general', max_length=30)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('recipient_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='enrollment.parent')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.school')),
            ],
            options={
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'recipient_user', 'is_read'], name='idx_notif_user_read'), models.Index(fields=['school', 'recipient_parent', 'is_read'], name='idx_notif_parent_read'), models.Index(fields=['school', 'type'], name='idx_notif_school_type')],
            },
        ),
    ]
