# Generated by Django 6.0.3 on 2026-03-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('result_release', 'Result Release'), ('attendance_alert', 'Attendance Alert'), ('fee_reminder', 'Fee Reminder'), ('system', 'System')], db_index=True, default='system', max_length=50),
        ),
    ]
