# Generated by Django 6.0.3 on 2026-03-07 21:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_school_branding_and_next_term_begins'),
        ('enrollment', '0004_parent_and_studentparent'),
        ('notifications', '0002_update_type_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(help_text='Recipient phone number in E.164 format, e.g. +2348012345678.', max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='enrollment.parent')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='enrollment.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='whatsapp_messages', to='core.term')),
            ],
            options={
                'db_table': 'notifications_whatsappmessage',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'status'], name='idx_wa_school_status'), models.Index(fields=['school', 'term', 'status'], name='idx_wa_school_term_status'), models.Index(fields=['school', 'parent'], name='idx_wa_school_parent')],
            },
        ),
    ]
