# Generated by Django 6.0.3 on 2026-03-06 07:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentType',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('weight', models.PositiveSmallIntegerField(help_text='Percentage contribution to the total score (all weights in a term must sum to 100).')),
                ('max_score', models.PositiveSmallIntegerField(editable=False, help_text='Maximum marks a student can score. Kept in sync with weight.')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Display order — lower numbers appear first.')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_types', to='core.school')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_types', to='core.term')),
            ],
            options={
                'db_table': 'academics_assessmenttype',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ResultStatistics',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('highest_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lowest_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('class_average', models.DecimalField(decimal_places=2, max_digits=6)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.school')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_statistics', to='core.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_statistics', to='core.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_statistics', to='core.term')),
            ],
            options={
                'verbose_name': 'Result Statistics',
                'verbose_name_plural': 'Result Statistics',
                'db_table': 'academics_resultstatistics',
                'ordering': ['school_class__name', 'subject__name'],
            },
        ),
        migrations.CreateModel(
            name='ResultSummary',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_score', models.DecimalField(decimal_places=2, help_text='Sum of all subject totals for this student in this term.', max_digits=8)),
                ('average_score', models.DecimalField(decimal_places=2, help_text='Mean subject score (total_score / number_of_subjects).', max_digits=6)),
                ('position', models.PositiveSmallIntegerField(blank=True, help_text='Class rank. NULL when school.enable_class_ranking is False.', null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.school')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_summaries', to='core.schoolclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_summaries', to='enrollment.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_summaries', to='core.term')),
            ],
            options={
                'verbose_name': 'Result Summary',
                'verbose_name_plural': 'Result Summaries',
                'db_table': 'academics_resultsummary',
                'ordering': ['term', 'position', 'student__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, help_text="Must be between 0 and the assessment type's max_score.", max_digits=6)),
                ('assessment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='academics.assessmenttype')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='enrollment.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='core.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='core.term')),
            ],
            options={
                'db_table': 'academics_score',
                'ordering': ['student__last_name', 'subject__name', 'assessment_type__order'],
            },
        ),
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.school')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_assignments', to='core.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_assignments', to='core.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_assignments', to='accounts.teacher')),
            ],
            options={
                'db_table': 'academics_teachingassignment',
                'ordering': ['school_class__name', 'subject__name'],
            },
        ),
        migrations.AddIndex(
            model_name='assessmenttype',
            index=models.Index(fields=['school', 'term'], name='idx_assessmenttype_school_term'),
        ),
        migrations.AddConstraint(
            model_name='assessmenttype',
            constraint=models.UniqueConstraint(fields=('school', 'term', 'name'), name='uniq_assessmenttype_name_per_school_term'),
        ),
        migrations.AddIndex(
            model_name='resultstatistics',
            index=models.Index(fields=['school', 'term'], name='idx_resultstat_school_term'),
        ),
        migrations.AddIndex(
            model_name='resultstatistics',
            index=models.Index(fields=['school', 'school_class', 'term'], name='idx_resultstat_cls_term'),
        ),
        migrations.AddConstraint(
            model_name='resultstatistics',
            constraint=models.UniqueConstraint(fields=('school', 'school_class', 'subject', 'term'), name='uniq_result_statistics_per_class_subject_term'),
        ),
        migrations.AddIndex(
            model_name='resultsummary',
            index=models.Index(fields=['school', 'school_class', 'term'], name='idx_resultsummary_class_term'),
        ),
        migrations.AddIndex(
            model_name='resultsummary',
            index=models.Index(fields=['school', 'term', 'average_score'], name='idx_resultsummary_term_avg'),
        ),
        migrations.AddConstraint(
            model_name='resultsummary',
            constraint=models.UniqueConstraint(fields=('school', 'student', 'term'), name='uniq_result_summary_student_term'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['school', 'student', 'term'], name='idx_score_school_student_term'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['school', 'subject', 'term'], name='idx_score_school_subject_term'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(fields=('school', 'student', 'subject', 'term', 'assessment_type'), name='uniq_score_per_student_subject_term_assessment'),
        ),
        migrations.AddIndex(
            model_name='teachingassignment',
            index=models.Index(fields=['school', 'teacher'], name='idx_assignment_school_teacher'),
        ),
        migrations.AddIndex(
            model_name='teachingassignment',
            index=models.Index(fields=['school', 'school_class'], name='idx_assignment_school_class'),
        ),
        migrations.AddIndex(
            model_name='teachingassignment',
            index=models.Index(fields=['school', 'subject'], name='idx_assignment_school_subject'),
        ),
        migrations.AddConstraint(
            model_name='teachingassignment',
            constraint=models.UniqueConstraint(fields=('school', 'teacher', 'school_class', 'subject'), name='uniq_teaching_assignment'),
        ),
    ]
