# Generated by Django 6.0.3 on 2026-03-06 10:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('core', '0001_initial'),
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubjectResult',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_score', models.DecimalField(decimal_places=2, help_text='Sum of all assessment scores for this student in this subject.', max_digits=6)),
                ('subject_position', models.PositiveSmallIntegerField(blank=True, help_text='Rank within the class for this subject. NULL when ranking is disabled.', null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.school')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_results', to='core.schoolclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_results', to='enrollment.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_results', to='core.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_results', to='core.term')),
            ],
            options={
                'verbose_name': 'Student Subject Result',
                'verbose_name_plural': 'Student Subject Results',
                'db_table': 'academics_studentsubjectresult',
                'ordering': ['term', 'subject__name', 'subject_position'],
                'indexes': [models.Index(fields=['school', 'school_class', 'term'], name='idx_subjresult_cls_term'), models.Index(fields=['school', 'student', 'term'], name='idx_subjresult_student_term')],
                'constraints': [models.UniqueConstraint(fields=('school', 'student', 'subject', 'term'), name='uniq_student_subject_result')],
            },
        ),
    ]
