# Generated by Django 6.0.3 on 2026-03-07 10:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_studentsubjectresult'),
        ('core', '0001_initial'),
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraitCategory',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('display_order', models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Display order — lower numbers appear first.')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.school')),
            ],
            options={
                'db_table': 'academics_traitcategory',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('display_order', models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Display order within its category — lower numbers appear first.')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.school')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traits', to='academics.traitcategory')),
            ],
            options={
                'db_table': 'academics_trait',
                'ordering': ['category__display_order', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TraitScale',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('numeric_value', models.PositiveSmallIntegerField(help_text='Numeric representation of this rating level.')),
                ('display_order', models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Display order — lower numbers appear first.')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.school')),
            ],
            options={
                'db_table': 'academics_traitscale',
                'ordering': ['display_order', '-numeric_value'],
            },
        ),
        migrations.CreateModel(
            name='StudentTraitRating',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trait_ratings', to='enrollment.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trait_ratings', to='core.term')),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratings', to='academics.trait')),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratings', to='academics.traitscale')),
            ],
            options={
                'db_table': 'academics_studenttraitrating',
                'ordering': ['student__last_name', 'term', 'trait__display_order'],
            },
        ),
        migrations.AddIndex(
            model_name='traitcategory',
            index=models.Index(fields=['school', 'display_order'], name='idx_traitcategory_school_order'),
        ),
        migrations.AddConstraint(
            model_name='traitcategory',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='uniq_traitcategory_name_per_school'),
        ),
        migrations.AddIndex(
            model_name='trait',
            index=models.Index(fields=['school', 'category'], name='idx_trait_school_category'),
        ),
        migrations.AddConstraint(
            model_name='trait',
            constraint=models.UniqueConstraint(fields=('school', 'category', 'name'), name='uniq_trait_name_per_category'),
        ),
        migrations.AddIndex(
            model_name='traitscale',
            index=models.Index(fields=['school', 'display_order'], name='idx_traitscale_school_order'),
        ),
        migrations.AddConstraint(
            model_name='traitscale',
            constraint=models.UniqueConstraint(fields=('school', 'label'), name='uniq_traitscale_label_per_school'),
        ),
        migrations.AddConstraint(
            model_name='traitscale',
            constraint=models.UniqueConstraint(fields=('school', 'numeric_value'), name='uniq_traitscale_value_per_school'),
        ),
        migrations.AddIndex(
            model_name='studenttraitrating',
            index=models.Index(fields=['school', 'student', 'term'], name='idx_traitrating_student_term'),
        ),
        migrations.AddConstraint(
            model_name='studenttraitrating',
            constraint=models.UniqueConstraint(fields=('school', 'student', 'term', 'trait'), name='uniq_student_trait_rating'),
        ),
    ]
