# Generated by Django 6.0.3 on 2026-03-07 12:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_traitcategory_trait_traitscale_studenttraitrating_and_more'),
        ('core', '0002_school_branding_and_next_term_begins'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCardTemplate',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Human-readable name for this template, e.g. 'Standard 2025'.", max_length=150)),
                ('html_template', models.TextField(help_text="Full HTML template string rendered with Django's template engine. Use {{ report }} and its nested keys as context variables.")),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='Only one template per school may be active at a time.')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.school')),
            ],
            options={
                'db_table': 'academics_reportcardtemplate',
                'ordering': ['school', 'name'],
                'indexes': [models.Index(fields=['school', 'is_active'], name='idx_reportcardtemplate_school_active')],
                'constraints': [models.UniqueConstraint(fields=('school', 'name'), name='uniq_reportcardtemplate_name_per_school'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('school',), name='uniq_active_reportcardtemplate_per_school')],
            },
        ),
    ]
