# Generated by Django 6.0.3 on 2026-03-07 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_reportcardtemplate'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reportcardtemplate',
            new_name='idx_rct_school_active',
            old_name='idx_reportcardtemplate_school_active',
        ),
    ]
