# Generated by Django 6.0.3 on 2026-03-07 15:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_result_release'),
        ('core', '0002_school_branding_and_next_term_begins'),
        ('enrollment', '0004_parent_and_studentparent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCardFile',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pdf_file', models.FileField(upload_to='reportcards/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_card_files', to='enrollment.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_card_files', to='core.term')),
            ],
            options={
                'db_table': 'academics_reportcardfile',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['school', 'student', 'term'], name='idx_rcfile_school_student_term')],
                'constraints': [models.UniqueConstraint(fields=('student', 'term'), name='uniq_reportcardfile_student_term')],
            },
        ),
    ]
