# Generated by Django 6.0.3 on 2026-03-07 23:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_school_branding_and_next_term_begins'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceAnalytics',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_sessions', models.PositiveIntegerField(default=0, help_text='Number of attendance sessions taken this term.')),
                ('total_records', models.PositiveIntegerField(default=0, help_text='Total attendance records (sessions × students).')),
                ('present_count', models.PositiveIntegerField(default=0)),
                ('absent_count', models.PositiveIntegerField(default=0)),
                ('late_count', models.PositiveIntegerField(default=0)),
                ('average_attendance_rate', models.DecimalField(decimal_places=2, default=0, help_text='(present + late) / total_records * 100.', max_digits=5)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.school')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_analytics', to='core.schoolclass')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_analytics', to='core.term')),
            ],
            options={
                'verbose_name': 'Attendance Analytics',
                'verbose_name_plural': 'Attendance Analytics',
                'db_table': 'analytics_attendanceanalytics',
                'ordering': ['school_class__name', '-term__start_date'],
                'indexes': [models.Index(fields=['school', 'term'], name='idx_attanalytics_school_term'), models.Index(fields=['school', 'school_class', 'term'], name='idx_attanalytics_cls_term')],
                'constraints': [models.UniqueConstraint(fields=('school', 'school_class', 'term'), name='uniq_attendanceanalytics_cls_term')],
            },
        ),
        migrations.CreateModel(
            name='ClassAnalytics',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('average_score', models.DecimalField(decimal_places=2, default=0, help_text='Mean of all student average scores in this class+term.', max_digits=6)),
                ('highest_average', models.DecimalField(decimal_places=2, default=0, help_text='Best individual average score in the class.', max_digits=6)),
                ('lowest_average', models.DecimalField(decimal_places=2, default=0, help_text='Worst individual average score in the class.', max_digits=6)),
                ('pass_rate', models.DecimalField(decimal_places=2, default=0, help_text='Percentage of students with average score >= 50.', max_digits=5)),
                ('subjects_offered', models.PositiveSmallIntegerField(default=0, help_text='Number of distinct subjects scored in this class+term.')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.school')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='core.schoolclass')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_analytics', to='core.term')),
            ],
            options={
                'verbose_name': 'Class Analytics',
                'verbose_name_plural': 'Class Analytics',
                'db_table': 'analytics_classanalytics',
                'ordering': ['school_class__name', '-term__start_date'],
                'indexes': [models.Index(fields=['school', 'term'], name='idx_classanalytics_school_term'), models.Index(fields=['school', 'school_class', 'term'], name='idx_classanalytics_cls_term')],
                'constraints': [models.UniqueConstraint(fields=('school', 'school_class', 'term'), name='uniq_classanalytics_cls_term')],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentAnalytics',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_enrolled', models.PositiveIntegerField(default=0)),
                ('male_count', models.PositiveIntegerField(default=0)),
                ('female_count', models.PositiveIntegerField(default=0)),
                ('class_count', models.PositiveSmallIntegerField(default=0, help_text='Number of distinct classes with enrolled students.')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.school')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_analytics', to='core.session')),
            ],
            options={
                'verbose_name': 'Enrollment Analytics',
                'verbose_name_plural': 'Enrollment Analytics',
                'db_table': 'analytics_enrollmentanalytics',
                'ordering': ['-session__start_date'],
                'indexes': [models.Index(fields=['school', 'session'], name='idx_enrollanalytics_school_session')],
                'constraints': [models.UniqueConstraint(fields=('school', 'session'), name='uniq_enrollmentanalytics_school_session')],
            },
        ),
        migrations.CreateModel(
            name='FinancialAnalytics',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_invoiced', models.DecimalField(decimal_places=2, default=0, help_text='Sum of all amount_due across invoices for this term.', max_digits=14)),
                ('total_collected', models.DecimalField(decimal_places=2, default=0, help_text='Sum of all amount_paid across invoices for this term.', max_digits=14)),
                ('total_outstanding', models.DecimalField(decimal_places=2, default=0, help_text='Sum of balance for unpaid/partially-paid invoices in this term.', max_digits=14)),
                ('collection_rate', models.DecimalField(decimal_places=2, default=0, help_text='total_collected / total_invoiced * 100 (percentage).', max_digits=5)),
                ('fully_paid_count', models.PositiveIntegerField(default=0, help_text='Number of invoices with status=PAID.')),
                ('partially_paid_count', models.PositiveIntegerField(default=0)),
                ('unpaid_count', models.PositiveIntegerField(default=0)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.school')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_analytics', to='core.term')),
            ],
            options={
                'verbose_name': 'Financial Analytics',
                'verbose_name_plural': 'Financial Analytics',
                'db_table': 'analytics_financialanalytics',
                'ordering': ['-term__start_date'],
                'indexes': [models.Index(fields=['school', 'term'], name='idx_finanalytics_school_term')],
                'constraints': [models.UniqueConstraint(fields=('school', 'term'), name='uniq_financialanalytics_school_term')],
            },
        ),
        migrations.CreateModel(
            name='SchoolDailyMetrics',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('active_students', models.PositiveIntegerField(default=0)),
                ('total_teachers', models.PositiveIntegerField(default=0)),
                ('active_teachers', models.PositiveIntegerField(default=0)),
                ('attendance_rate', models.DecimalField(decimal_places=2, default=0, help_text='Attendance rate for the day as a percentage (0–100).', max_digits=5)),
                ('total_attendance_records', models.PositiveIntegerField(default=0)),
                ('present_count', models.PositiveIntegerField(default=0)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.school')),
            ],
            options={
                'verbose_name': 'School Daily Metrics',
                'verbose_name_plural': 'School Daily Metrics',
                'db_table': 'analytics_schooldailymetrics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['school', 'date'], name='idx_sdm_school_date')],
                'constraints': [models.UniqueConstraint(fields=('school', 'date'), name='uniq_schooldailymetrics_school_date')],
            },
        ),
        migrations.CreateModel(
            name='SubjectAnalytics',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('average_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('highest_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('lowest_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('pass_rate', models.DecimalField(decimal_places=2, default=0, help_text='Percentage of students with total_score >= 50 in this subject.', max_digits=5)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.school')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_analytics', to='core.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='core.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_analytics', to='core.term')),
            ],
            options={
                'verbose_name': 'Subject Analytics',
                'verbose_name_plural': 'Subject Analytics',
                'db_table': 'analytics_subjectanalytics',
                'ordering': ['subject__name', '-term__start_date'],
                'indexes': [models.Index(fields=['school', 'term'], name='idx_subjectanalytics_school_term'), models.Index(fields=['school', 'subject', 'term'], name='idx_subjectanalytics_subj_term')],
                'constraints': [models.UniqueConstraint(fields=('school', 'subject', 'school_class', 'term'), name='uniq_subjectanalytics_subj_cls_term')],
            },
        ),
    ]
