# Generated by Django 6.0.3 on 2026-03-07 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='enrollmentanalytics',
            new_name='idx_enrollanal_school_session',
            old_name='idx_enrollanalytics_school_session',
        ),
        migrations.RenameIndex(
            model_name='subjectanalytics',
            new_name='idx_subjanal_school_term',
            old_name='idx_subjectanalytics_school_term',
        ),
    ]
