# Generated by Django 6.0.3 on 2026-03-07 15:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_school_branding_and_next_term_begins'),
        ('enrollment', '0004_parent_and_studentparent'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInvoice',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, editable=False, help_text='Auto-computed: amount_due − amount_paid.', max_digits=10)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid')], db_index=True, default='unpaid', max_length=10)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='enrollment.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.term')),
            ],
            options={
                'db_table': 'finance_studentinvoice',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card'), ('mobile_money', 'Mobile Money')], db_index=True, default='cash', max_length=20)),
                ('transaction_reference', models.CharField(help_text='Unique reference code for this payment (auto-generated if not supplied).', max_length=100, unique=True)),
                ('paid_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to='enrollment.student')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.studentinvoice')),
            ],
            options={
                'db_table': 'finance_paymenttransaction',
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tuition_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('development_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('sports_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('exam_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, help_text='Auto-computed: sum of all fee components.', max_digits=10)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.school')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='core.schoolclass')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='core.term')),
            ],
            options={
                'db_table': 'finance_feestructure',
                'ordering': ['school_class__name', 'term__name'],
                'indexes': [models.Index(fields=['school', 'term'], name='idx_feestructure_school_term'), models.Index(fields=['school', 'school_class', 'term'], name='idx_feestructure_cls_term')],
                'constraints': [models.UniqueConstraint(fields=('school_class', 'term'), name='uniq_feestructure_class_term')],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('pdf_file', models.FileField(blank=True, help_text='Generated PDF receipt file.', null=True, upload_to='receipts/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.school')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='finance.paymenttransaction')),
            ],
            options={
                'db_table': 'finance_receipt',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['school', 'receipt_number'], name='idx_receipt_school_number')],
            },
        ),
        migrations.AddIndex(
            model_name='studentinvoice',
            index=models.Index(fields=['school', 'student'], name='idx_invoice_school_student'),
        ),
        migrations.AddIndex(
            model_name='studentinvoice',
            index=models.Index(fields=['school', 'term', 'status'], name='idx_invoice_school_term_status'),
        ),
        migrations.AddConstraint(
            model_name='studentinvoice',
            constraint=models.UniqueConstraint(fields=('student', 'term'), name='uniq_invoice_student_term'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['school', 'student'], name='idx_payment_school_student'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['school', 'invoice'], name='idx_payment_school_invoice'),
        ),
    ]
