# Generated by Django 6.0.3 on 2026-03-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_school_branding_and_next_term_begins'),
        ('enrollment', '0006_index_audit_score'),
        ('finance', '0002_update_models'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['school', 'student', 'created_at'], name='idx_payment_student_created'),
        ),
        migrations.AddIndex(
            model_name='studentinvoice',
            index=models.Index(fields=['school', 'student', 'status'], name='idx_invoice_student_status'),
        ),
    ]
