# Generated by Django 6.0.3 on 2026-03-07 21:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_school_branding_and_next_term_begins'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, help_text='Dot-namespaced action identifier, e.g. "result.publish".', max_length=100)),
                ('target_model', models.CharField(db_index=True, help_text='The Django model class name that was acted upon.', max_length=100)),
                ('target_id', models.UUIDField(blank=True, help_text='Primary key of the affected model instance.', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Arbitrary contextual data about the action.', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Exact UTC time the action was recorded.')),
                ('actor', models.ForeignKey(blank=True, help_text='The user who triggered the action. Null for system actions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.school')),
            ],
            options={
                'db_table': 'audit_auditlog',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['school', 'action'], name='idx_audit_school_action'), models.Index(fields=['school', 'actor'], name='idx_audit_school_actor'), models.Index(fields=['school', 'target_model', 'target_id'], name='idx_audit_school_target')],
            },
        ),
    ]
