# Generated by Django 6.0.3 on 2026-03-06 07:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('school_type', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('combined', 'Combined')], max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='schools/logos/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('deactivated', 'Deactivated')], db_index=True, default='active', max_length=20)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('enable_class_ranking', models.BooleanField(default=True, help_text='When enabled, students are ranked by average score on their result sheets.')),
            ],
            options={
                'db_table': 'core_school',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='idx_school_slug'), models.Index(fields=['status'], name='idx_school_status')],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. "2024/2025"', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.school')),
            ],
            options={
                'db_table': 'core_session',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, help_text='Short subject code, e.g. MTH, ENG. Optional but unique per school when set.', max_length=20)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.school')),
            ],
            options={
                'db_table': 'core_subject',
                'ordering': ['school', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('term_number', models.IntegerField(choices=[(1, 'First Term'), (2, 'Second Term'), (3, 'Third Term')])),
                ('name', models.CharField(blank=True, help_text='Auto-populated from term_number if left blank, e.g. "First Term".', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.school')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terms', to='core.session')),
            ],
            options={
                'db_table': 'core_term',
                'ordering': ['session__start_date', 'term_number'],
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Display order — lower numbers appear first.')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.school')),
            ],
            options={
                'db_table': 'core_schoolclass',
                'ordering': ['school', 'order', 'name'],
                'indexes': [models.Index(fields=['school', 'order'], name='idx_schoolclass_school_order')],
                'constraints': [models.UniqueConstraint(fields=('school', 'name'), name='uniq_schoolclass_name_per_school')],
            },
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['school', 'is_active'], name='idx_session_school_active'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['school', 'start_date'], name='idx_session_school_start'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('school',), name='uniq_active_session_per_school'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='uniq_session_name_per_school'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['school', 'name'], name='idx_subject_school_name'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='uniq_subject_name_per_school'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(condition=models.Q(('code__gt', '')), fields=('school', 'code'), name='uniq_subject_code_per_school'),
        ),
        migrations.AddIndex(
            model_name='term',
            index=models.Index(fields=['school', 'is_active'], name='idx_term_school_active'),
        ),
        migrations.AddIndex(
            model_name='term',
            index=models.Index(fields=['session', 'is_active'], name='idx_term_session_active'),
        ),
        migrations.AddIndex(
            model_name='term',
            index=models.Index(fields=['session', 'start_date'], name='idx_term_session_start'),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('session',), name='uniq_active_term_per_session'),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(fields=('session', 'term_number'), name='uniq_term_number_per_session'),
        ),
    ]
