# Generated by Django 6.0.3 on 2026-03-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='principal_signature',
            field=models.ImageField(blank=True, help_text="Principal's signature image printed at the bottom of report cards.", null=True, upload_to='schools/signatures/'),
        ),
        migrations.AddField(
            model_name='school',
            name='school_stamp',
            field=models.ImageField(blank=True, help_text='Official school stamp image printed at the bottom-right of report cards.', null=True, upload_to='schools/stamps/'),
        ),
        migrations.AddField(
            model_name='term',
            name='next_term_begins',
            field=models.DateField(blank=True, help_text='Date the next term begins, printed on report cards.', null=True),
        ),
    ]
