# Generated by Django 6.0.3 on 2026-03-06 07:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_number', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('graduated', 'Graduated'), ('withdrawn', 'Withdrawn'), ('suspended', 'Suspended')], db_index=True, default='active', max_length=20)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.school')),
                ('student_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.schoolclass')),
            ],
            options={
                'db_table': 'enrollment_student',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['school', 'status'], name='idx_student_school_status'), models.Index(fields=['school', 'last_name', 'first_name'], name='idx_student_school_name'), models.Index(fields=['school', 'registration_number'], name='idx_student_school_reg')],
                'constraints': [models.UniqueConstraint(fields=('school', 'registration_number'), name='uniq_student_reg_number_per_school')],
            },
        ),
    ]
