# Generated by Django 6.0.3 on 2026-03-07 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_attendance_session_and_record'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendancerecord',
            new_name='idx_attrec_school_student',
            old_name='idx_attendancerecord_school_student',
        ),
        migrations.RenameIndex(
            model_name='attendancerecord',
            new_name='idx_attrec_session_status',
            old_name='idx_attendancerecord_session_status',
        ),
        migrations.RenameIndex(
            model_name='attendancesession',
            new_name='idx_attsession_school_date',
            old_name='idx_attendancesession_school_date',
        ),
        migrations.RenameIndex(
            model_name='attendancesession',
            new_name='idx_attsession_cls_date',
            old_name='idx_attendancesession_cls_date',
        ),
    ]
