# Generated by Django 6.0.3 on 2026-03-07 14:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_school_branding_and_next_term_begins'),
        ('enrollment', '0003_fix_attendance_index_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.school')),
            ],
            options={
                'db_table': 'enrollment_parent',
                'ordering': ['school', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudentParent',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship', models.CharField(help_text='e.g. "Mother", "Father", "Guardian".', max_length=100)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_parents', to='enrollment.parent')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_parents', to='enrollment.student')),
            ],
            options={
                'db_table': 'enrollment_studentparent',
                'ordering': ['student__last_name', 'parent__name'],
            },
        ),
        migrations.AddIndex(
            model_name='parent',
            index=models.Index(fields=['school', 'name'], name='idx_parent_school_name'),
        ),
        migrations.AddIndex(
            model_name='studentparent',
            index=models.Index(fields=['school', 'student'], name='idx_stpar_school_student'),
        ),
        migrations.AddIndex(
            model_name='studentparent',
            index=models.Index(fields=['school', 'parent'], name='idx_stpar_school_parent'),
        ),
        migrations.AddConstraint(
            model_name='studentparent',
            constraint=models.UniqueConstraint(fields=('student', 'parent'), name='uniq_student_parent'),
        ),
    ]
