# Generated by Django 6.0.3 on 2026-03-07 21:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_school_branding_and_next_term_begins'),
        ('enrollment', '0004_parent_and_studentparent'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.school')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='core.schoolclass')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='core.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='enrollment.student')),
            ],
            options={
                'db_table': 'enrollment_studentenrollment',
                'ordering': ['-session__start_date'],
                'indexes': [models.Index(fields=['school', 'school_class', 'session'], name='idx_enroll_cls_session'), models.Index(fields=['school', 'student'], name='idx_enroll_school_student'), models.Index(fields=['school', 'is_current'], name='idx_enroll_school_current')],
                'constraints': [models.UniqueConstraint(fields=('student', 'session'), name='uniq_enrollment_student_session')],
            },
        ),
    ]
