# Generated by Django 6.0.3 on 2026-03-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_school_branding_and_next_term_begins'),
        ('enrollment', '0005_studentenrollment'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['school', 'student', 'session'], name='idx_attrec_student_session'),
        ),
    ]
